/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sD4RZdWHksD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export default function harvardreviewessay() {
  return (
    <div key="1" className="min-h-screen bg-gradient-to-b from-black to-[#a51c30] text-white">
      <div className="flex flex-col items-center justify-center py-12">
        <img
          alt="Harvard Logo"
          className="mb-4"
          height="100"
          src="/placeholder.svg"
          style={{
            aspectRatio: "100/100",
            objectFit: "cover",
          }}
          width="100"
        />
        <h1 className="text-4xl font-bold mb-2">Harvard Essay Review</h1>
        <p className="text-xl mb-8">Get your college essay reviewed by a Harvard student for only $5!</p>
        <div className="bg-gradient-to-r from-[#a51c30] to-[#8b1a2a] p-6 rounded-lg shadow-lg text-center mb-8">
          <p className="font-bold text-2xl mb-2">Special Offer!</p>
          <p className="mb-4">A high-quality review at an unbeatable price.</p>
          <Button className="bg-white text-black">
            <a href="#">Order Now</a>
          </Button>
        </div>
        <form className="w-full max-w-lg space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" placeholder="Enter your name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="social">Social Media (Instagram or Discord)</Label>
            <Input id="social" placeholder="Enter your Instagram or Discord handle" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="google-docs">Google Docs Link</Label>
            <Input placeholder="Enter the link to your essay on Google Docs" />
            <p className="text-xs text-gray-400">Please ensure you provide suggesting or editing access.</p>
          </div>
          <Button className="w-full bg-white text-[#a51c30]">Submit for Review</Button>
        </form>
      </div>
      <footer className="text-center py-4 border-t border-gray-700 mt-12">
        <p>Website created and designed by Kim Khoi Lam</p>
      </footer>
    </div>
  )
}
